/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
import Project.ConProv;
import java.sql.*;
import javax.swing.JOptionPane;

public class NewMember extends javax.swing.JFrame {

    /**
     * Creates new form NewMember
     */
    public NewMember() {
        initComponents();
        try
        {
            int id=1;
            String str1=String.valueOf(id);
            mid.setText(str1);
            Connection con = ConProv.Getcon();
            Statement s = con.createStatement();
            ResultSet r = s.executeQuery("select max(MID) from Member");
            while(r.next())
            {
                id=r.getInt(1);
                id++;
                String str = String.valueOf(id);
                mid.setText(str);
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Name = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        mobile = new javax.swing.JLabel();
        txtmob = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        age = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        Fname = new javax.swing.JLabel();
        txtmname = new javax.swing.JTextField();
        Mname = new javax.swing.JLabel();
        timing = new javax.swing.JLabel();
        cbgender = new javax.swing.JComboBox<>();
        txtaadhar = new javax.swing.JTextField();
        Aadhar = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();
        bback = new javax.swing.JButton();
        bsave = new javax.swing.JButton();
        bclear = new javax.swing.JButton();
        mid = new javax.swing.JLabel();
        cbtimings = new javax.swing.JComboBox<>();
        txtamount = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(175, 100));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("ADD NEW MEMBER");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 44, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 91, 980, 10));

        Name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Name.setText("Name");
        jPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Member ID : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 190, -1));

        mobile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mobile.setText("Mobile");
        jPanel1.add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));
        jPanel1.add(txtmob, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 190, -1));
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 190, -1));

        email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        email.setText("Email");
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        gender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gender.setText("Gender");
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));
        jPanel1.add(txtage, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 190, -1));

        age.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        age.setText("Age");
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, -1, -1));
        jPanel1.add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 190, -1));

        Fname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Fname.setText("Father's Name");
        jPanel1.add(Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, -1, -1));
        jPanel1.add(txtmname, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 190, -1));

        Mname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Mname.setText("Mother's Name");
        jPanel1.add(Mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, -1, -1));

        timing.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        timing.setText("Gym Timings");
        jPanel1.add(timing, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, -1, -1));

        cbgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        jPanel1.add(cbgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 190, -1));
        jPanel1.add(txtaadhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 190, -1));

        Aadhar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Aadhar.setText("Aadhar Number");
        jPanel1.add(Aadhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, -1, -1));

        amount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        amount.setText("Amount(/month)");
        jPanel1.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, -1, -1));

        bback.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bback.setText("Back");
        bback.setMargin(new java.awt.Insets(4, 18, 4, 18));
        bback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bbackMouseClicked(evt);
            }
        });
        bback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbackActionPerformed(evt);
            }
        });
        jPanel1.add(bback, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 550, -1, -1));

        bsave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bsave.setText("Save");
        bsave.setMargin(new java.awt.Insets(4, 18, 4, 18));
        bsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsaveActionPerformed(evt);
            }
        });
        jPanel1.add(bsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 550, -1, -1));

        bclear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bclear.setText("Clear");
        bclear.setMargin(new java.awt.Insets(4, 18, 4, 18));
        bclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclearActionPerformed(evt);
            }
        });
        jPanel1.add(bclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 550, -1, -1));

        mid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mid.setForeground(new java.awt.Color(255, 0, 0));
        mid.setText("00");
        jPanel1.add(mid, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        cbtimings.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbtimings.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "06:00 - 11:00", "17:00 - 21:00" }));
        jPanel1.add(cbtimings, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 190, -1));
        jPanel1.add(txtamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbackActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_bbackActionPerformed

    private void bbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbackMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bbackMouseClicked

    private void bclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclearActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new NewMember().setVisible(true);
    }//GEN-LAST:event_bclearActionPerformed

    private void bsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsaveActionPerformed
        // TODO add your handling code here:
        String id = mid.getText();
        String name = txtname.getText();
        String mob = txtmob.getText();
        String email = txtemail.getText();
        String gender = (String)cbgender.getSelectedItem();
        String age = txtage.getText();
        String fname = txtfname.getText();
        String mname = txtmname.getText();
        String time = (String)cbtimings.getSelectedItem();
        String aadhar = txtaadhar.getText();
        String amount = txtamount.getText();
        
        try
        {
            Connection con = ConProv.Getcon();
            PreparedStatement s = con.prepareStatement("insert into Member values(?,?,?,?,?,?,?,?,?,?,?)");
            s.setString(1, id);
            s.setString(2, name);
            s.setString(3, mob);
            s.setString(4, email);
            s.setString(5, gender);
            s.setString(6, fname);
            s.setString(7, mname);
            s.setString(8, time);
            s.setString(9, aadhar);
            s.setString(10, age);
            s.setString(11, amount);
            s.executeUpdate();
            JOptionPane.showMessageDialog(this, "Successfully Updated!!!");
            setVisible(false);
            new NewMember().setVisible(true);
                    
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex);       
        }
    }//GEN-LAST:event_bsaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aadhar;
    private javax.swing.JLabel Fname;
    private javax.swing.JLabel Mname;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel age;
    private javax.swing.JLabel amount;
    private javax.swing.JButton bback;
    private javax.swing.JButton bclear;
    private javax.swing.JButton bsave;
    private javax.swing.JComboBox<String> cbgender;
    private javax.swing.JComboBox<String> cbtimings;
    private javax.swing.JLabel email;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mid;
    private javax.swing.JLabel mobile;
    private javax.swing.JLabel timing;
    private javax.swing.JTextField txtaadhar;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtamount;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtmname;
    private javax.swing.JTextField txtmob;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
