/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
import java.sql.*;
import Project.ConProv;
import com.mysql.cj.xdevapi.PreparableStatement;
import javax.swing.JOptionPane;

public class Update extends javax.swing.JFrame {

    /**
     * Creates new form Update
     */
    public Update() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtmid = new javax.swing.JTextField();
        bsearch = new javax.swing.JButton();
        Name = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        mob = new javax.swing.JLabel();
        txtmob = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        Gender = new javax.swing.JLabel();
        txtgender = new javax.swing.JTextField();
        age = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        Fname = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        Mname = new javax.swing.JLabel();
        txttiming = new javax.swing.JTextField();
        timings = new javax.swing.JLabel();
        aadhar = new javax.swing.JLabel();
        txtaadhar = new javax.swing.JTextField();
        amount = new javax.swing.JLabel();
        txtamount = new javax.swing.JTextField();
        txtmname = new javax.swing.JTextField();
        bback = new javax.swing.JButton();
        bupdate = new javax.swing.JButton();
        bdelete = new javax.swing.JButton();
        breset1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(175, 100));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 220, 137));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Update/Delete Member");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 26, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 72, 980, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Member ID: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));
        jPanel1.add(txtmid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 120, -1));

        bsearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bsearch.setText("Search");
        bsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsearchActionPerformed(evt);
            }
        });
        jPanel1.add(bsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Name.setText("Name");
        jPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        txtname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 330, -1));

        mob.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mob.setText("Mobile Number");
        jPanel1.add(mob, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        txtmob.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtmob, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 330, -1));

        email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        email.setText("Email");
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        txtemail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 330, -1));

        Gender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Gender.setText("Gender");
        jPanel1.add(Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        txtgender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 330, -1));

        age.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        age.setText("Age");
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        txtage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtage, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 330, -1));

        Fname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Fname.setText("Father's Name");
        jPanel1.add(Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, -1, -1));

        txtfname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 330, -1));

        Mname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Mname.setText("Mother's Name");
        jPanel1.add(Mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, -1, -1));

        txttiming.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txttiming, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 330, -1));

        timings.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        timings.setText("Gym Timings");
        jPanel1.add(timings, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, -1, -1));

        aadhar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        aadhar.setText("Aadhar Number");
        jPanel1.add(aadhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, -1));

        txtaadhar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtaadhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 330, -1));

        amount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        amount.setText("Amount(/month)");
        jPanel1.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, -1, -1));

        txtamount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, 330, -1));

        txtmname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtmname, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 330, -1));

        bback.setText("Back");
        bback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbackActionPerformed(evt);
            }
        });
        jPanel1.add(bback, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, -1, -1));

        bupdate.setText("Update");
        bupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupdateActionPerformed(evt);
            }
        });
        jPanel1.add(bupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, -1, -1));

        bdelete.setText("Delete");
        bdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdeleteActionPerformed(evt);
            }
        });
        jPanel1.add(bdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, -1, -1));

        breset1.setText("Reset");
        breset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breset1ActionPerformed(evt);
            }
        });
        jPanel1.add(breset1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbackActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_bbackActionPerformed

    private void breset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breset1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Update().setVisible(true);
    }//GEN-LAST:event_breset1ActionPerformed

    private void bsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsearchActionPerformed
        // TODO add your handling code here:
        int checkid=0;
        String id = txtmid.getText();
        try
        {
            Connection con = ConProv.Getcon();
            Statement s = con.createStatement();
            ResultSet r = s.executeQuery("select * from Member where MID = '"+id+"'");
            while(r.next())
            {
                checkid=1;
                txtmid.setEditable(false);
                txtname.setText(r.getString(2));
                txtmob.setText(r.getString(3));
                txtemail.setText(r.getString(4));
                txtgender.setText(r.getString(5));
                txtgender.setEditable(false);
                txtage.setText(r.getString(10));
                txtfname.setText(r.getString(6));
                txtmname.setText(r.getString(7));
                txttiming.setText(r.getString(8));
                txttiming.setEditable(false);
                txtaadhar.setText(r.getString(9));
                txtamount.setText(r.getString(11));
            }
            if(checkid==0)
                JOptionPane.showMessageDialog(this, "Member ID does not exist!");
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_bsearchActionPerformed

    private void bupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdateActionPerformed
        // TODO add your handling code here:
        String id=txtmid.getText();
        String name=txtname.getText();
        String mob=txtmob.getText();
        String email=txtemail.getText();
        String fname=txtfname.getText();
        String mname=txtmname.getText();
        String aadhar=txtaadhar.getText();
        String age=txtage.getText();
        String amount=txtamount.getText();
        try
        {
            Connection con = ConProv.Getcon();
            PreparedStatement s = con.prepareStatement("update Member set Name=?,mobile=?,email=?,Fname=?,Mname=?,Aadhar=?,age=?,amount=? where MID=?");
            s.setString(1,name);
            s.setString(2,mob);
            s.setString(3,email);
            s.setString(4,fname);
            s.setString(5,mname);
            s.setString(6,aadhar);
            s.setString(7,age);
            s.setString(8,amount);
            s.setString(9,id);
            s.executeUpdate();
            JOptionPane.showMessageDialog(this, "Successfully Updated!");
            setVisible(false);
            new Update().setVisible(true);
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex);
        }
        
    }//GEN-LAST:event_bupdateActionPerformed

    private void bdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdeleteActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete the Member?","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            String id = txtmid.getText();
            try
            {
                Connection con = ConProv.Getcon();
                Statement s = con.createStatement();
                s.executeUpdate("delete from Member where MID='"+id+"'");
                JOptionPane.showMessageDialog(this, "Member Successfully deleted!");
                setVisible(false);
                new Update().setVisible(true);
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(this, ex);
            }
        }
    }//GEN-LAST:event_bdeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fname;
    private javax.swing.JLabel Gender;
    private javax.swing.JLabel Mname;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel aadhar;
    private javax.swing.JLabel age;
    private javax.swing.JLabel amount;
    private javax.swing.JButton bback;
    private javax.swing.JButton bdelete;
    private javax.swing.JButton breset1;
    private javax.swing.JButton bsearch;
    private javax.swing.JButton bupdate;
    private javax.swing.JLabel email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mob;
    private javax.swing.JLabel timings;
    private javax.swing.JTextField txtaadhar;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtamount;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtmid;
    private javax.swing.JTextField txtmname;
    private javax.swing.JTextField txtmob;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txttiming;
    // End of variables declaration//GEN-END:variables
}
